services:
  pg:
    image: debezium/postgres:14
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/bitnami/postgresql"
      - "./conf.d/:/bitnami/postgresql/conf/conf.d/"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "meroxadb", "-U", "meroxauser" ]
      timeout: 30s
      interval: 10s
      retries: 5
    environment:
      - POSTGRES_USER=meroxauser
      - POSTGRES_PASSWORD=meroxapass
      - POSTGRES_DB=meroxadb

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    healthcheck:
      test: kafka-topics --list --bootstrap-server localhost:9092
      # healthchecks happen every 10s, failures in the first 30s are not counted toward the maximum number of retries,
      # after 3 failed healthchecks the service is marked as unhealthy
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  init-kafka:
    image: confluentinc/cp-kafka:7.0.0
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:29092 --list
      
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic flink-topic-source --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic flink-topic-sink --replication-factor 1 --partitions 1
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "
volumes:
  pg_data:
    driver: local
