/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.conduit.client.model.Configv1ParameterType;
import io.conduit.client.model.Configv1Validation;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Parameter describes a single config parameter.
 */
@ApiModel(description = "Parameter describes a single config parameter.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-13T16:13:27.395+01:00")
public class Configv1Parameter {
  @SerializedName("default")
  private String _default = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("type")
  private Configv1ParameterType type = null;

  @SerializedName("validations")
  private List<Configv1Validation> validations = null;

  public Configv1Parameter _default(String _default) {
    this._default = _default;
    return this;
  }

   /**
   * Default is the default value of the parameter. If there is no default value use an empty string.
   * @return _default
  **/
  @ApiModelProperty(value = "Default is the default value of the parameter. If there is no default value use an empty string.")
  public String getDefault() {
    return _default;
  }

  public void setDefault(String _default) {
    this._default = _default;
  }

  public Configv1Parameter description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description explains what the parameter does and how to configure it.
   * @return description
  **/
  @ApiModelProperty(value = "Description explains what the parameter does and how to configure it.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Configv1Parameter type(Configv1ParameterType type) {
    this.type = type;
    return this;
  }

   /**
   * Type defines the parameter data type.
   * @return type
  **/
  @ApiModelProperty(value = "Type defines the parameter data type.")
  public Configv1ParameterType getType() {
    return type;
  }

  public void setType(Configv1ParameterType type) {
    this.type = type;
  }

  public Configv1Parameter validations(List<Configv1Validation> validations) {
    this.validations = validations;
    return this;
  }

  public Configv1Parameter addValidationsItem(Configv1Validation validationsItem) {
    if (this.validations == null) {
      this.validations = new ArrayList<Configv1Validation>();
    }
    this.validations.add(validationsItem);
    return this;
  }

   /**
   * Validations are validations to be made on the parameter.
   * @return validations
  **/
  @ApiModelProperty(value = "Validations are validations to be made on the parameter.")
  public List<Configv1Validation> getValidations() {
    return validations;
  }

  public void setValidations(List<Configv1Validation> validations) {
    this.validations = validations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Configv1Parameter configv1Parameter = (Configv1Parameter) o;
    return Objects.equals(this._default, configv1Parameter._default) &&
        Objects.equals(this.description, configv1Parameter.description) &&
        Objects.equals(this.type, configv1Parameter.type) &&
        Objects.equals(this.validations, configv1Parameter.validations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_default, description, type, validations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Configv1Parameter {\n");
    
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    validations: ").append(toIndentedString(validations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

