/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.conduit.client.model.Configv1ValidationType;
import java.io.IOException;

/**
 * Validation to be made on the parameter.
 */
@ApiModel(description = "Validation to be made on the parameter.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-13T16:13:27.395+01:00")
public class Configv1Validation {
  @SerializedName("type")
  private Configv1ValidationType type = null;

  @SerializedName("value")
  private String value = null;

  public Configv1Validation type(Configv1ValidationType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public Configv1ValidationType getType() {
    return type;
  }

  public void setType(Configv1ValidationType type) {
    this.type = type;
  }

  public Configv1Validation value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The value to be compared with the parameter, or a comma separated list in case of Validation.TYPE_INCLUSION or Validation.TYPE_EXCLUSION.
   * @return value
  **/
  @ApiModelProperty(value = "The value to be compared with the parameter, or a comma separated list in case of Validation.TYPE_INCLUSION or Validation.TYPE_EXCLUSION.")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Configv1Validation configv1Validation = (Configv1Validation) o;
    return Objects.equals(this.type, configv1Validation.type) &&
        Objects.equals(this.value, configv1Validation.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Configv1Validation {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

