/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  - TYPE_REQUIRED: Parameter must be present.  - TYPE_GREATER_THAN: Parameter must be greater than {value}.  - TYPE_LESS_THAN: Parameter must be less than {value}.  - TYPE_INCLUSION: Parameter must be included in the comma separated list {value}.  - TYPE_EXCLUSION: Parameter must not be included in the comma separated list {value}.  - TYPE_REGEX: Parameter must match the regex {value}.
 */
@JsonAdapter(Configv1ValidationType.Adapter.class)
public enum Configv1ValidationType {
  
  UNSPECIFIED("TYPE_UNSPECIFIED"),
  
  REQUIRED("TYPE_REQUIRED"),
  
  GREATER_THAN("TYPE_GREATER_THAN"),
  
  LESS_THAN("TYPE_LESS_THAN"),
  
  INCLUSION("TYPE_INCLUSION"),
  
  EXCLUSION("TYPE_EXCLUSION"),
  
  REGEX("TYPE_REGEX");

  private String value;

  Configv1ValidationType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Configv1ValidationType fromValue(String text) {
    for (Configv1ValidationType b : Configv1ValidationType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Configv1ValidationType> {
    @Override
    public void write(final JsonWriter jsonWriter, final Configv1ValidationType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Configv1ValidationType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Configv1ValidationType.fromValue(String.valueOf(value));
    }
  }
}

