/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.conduit.client.model.V1Data;
import java.io.IOException;

/**
 * Change represents the data before and after the operation occurred.
 */
@ApiModel(description = "Change represents the data before and after the operation occurred.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-13T16:13:27.395+01:00")
public class V1Change {
  @SerializedName("before")
  private V1Data before = null;

  @SerializedName("after")
  private V1Data after = null;

  public V1Change before(V1Data before) {
    this.before = before;
    return this;
  }

   /**
   * Before contains the data before the operation occurred. This field is optional and should only be populated for operations \&quot;update\&quot; and \&quot;delete\&quot; (if the system supports fetching the data before the operation).
   * @return before
  **/
  @ApiModelProperty(value = "Before contains the data before the operation occurred. This field is optional and should only be populated for operations \"update\" and \"delete\" (if the system supports fetching the data before the operation).")
  public V1Data getBefore() {
    return before;
  }

  public void setBefore(V1Data before) {
    this.before = before;
  }

  public V1Change after(V1Data after) {
    this.after = after;
    return this;
  }

   /**
   * After contains the data after the operation occurred. This field should be populated for all operations except \&quot;delete\&quot;.
   * @return after
  **/
  @ApiModelProperty(value = "After contains the data after the operation occurred. This field should be populated for all operations except \"delete\".")
  public V1Data getAfter() {
    return after;
  }

  public void setAfter(V1Data after) {
    this.after = after;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1Change v1Change = (V1Change) o;
    return Objects.equals(this.before, v1Change.before) &&
        Objects.equals(this.after, v1Change.after);
  }

  @Override
  public int hashCode() {
    return Objects.hash(before, after);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1Change {\n");
    
    sb.append("    before: ").append(toIndentedString(before)).append("\n");
    sb.append("    after: ").append(toIndentedString(after)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

