/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Type shows the connector type.   - TYPE_SOURCE: Connector is a source.  - TYPE_DESTINATION: Connector is a destination.
 */
@JsonAdapter(V1ConnectorType.Adapter.class)
public enum V1ConnectorType {
  
  UNSPECIFIED("TYPE_UNSPECIFIED"),
  
  SOURCE("TYPE_SOURCE"),
  
  DESTINATION("TYPE_DESTINATION");

  private String value;

  V1ConnectorType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static V1ConnectorType fromValue(String text) {
    for (V1ConnectorType b : V1ConnectorType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<V1ConnectorType> {
    @Override
    public void write(final JsonWriter jsonWriter, final V1ConnectorType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public V1ConnectorType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return V1ConnectorType.fromValue(String.valueOf(value));
    }
  }
}

