/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Data is used to represent the record key and payload. It can be either raw data (byte array) or structured data (struct).
 */
@ApiModel(description = "Data is used to represent the record key and payload. It can be either raw data (byte array) or structured data (struct).")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-13T16:13:27.395+01:00")
public class V1Data {
  @SerializedName("rawData")
  private byte[] rawData = null;

  @SerializedName("structuredData")
  private Object structuredData = null;

  public V1Data rawData(byte[] rawData) {
    this.rawData = rawData;
    return this;
  }

   /**
   * Raw data contains unstructured data in form of a byte array.
   * @return rawData
  **/
  @ApiModelProperty(value = "Raw data contains unstructured data in form of a byte array.")
  public byte[] getRawData() {
    return rawData;
  }

  public void setRawData(byte[] rawData) {
    this.rawData = rawData;
  }

  public V1Data structuredData(Object structuredData) {
    this.structuredData = structuredData;
    return this;
  }

   /**
   * Structured data contains data in form of a struct with fields.
   * @return structuredData
  **/
  @ApiModelProperty(value = "Structured data contains data in form of a struct with fields.")
  public Object getStructuredData() {
    return structuredData;
  }

  public void setStructuredData(Object structuredData) {
    this.structuredData = structuredData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1Data v1Data = (V1Data) o;
    return Arrays.equals(this.rawData, v1Data.rawData) &&
        Objects.equals(this.structuredData, v1Data.structuredData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Arrays.hashCode(rawData), structuredData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1Data {\n");
    
    sb.append("    rawData: ").append(toIndentedString(rawData)).append("\n");
    sb.append("    structuredData: ").append(toIndentedString(structuredData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

