/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.conduit.client.model.V1Processor;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1ListProcessorsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-13T16:13:27.395+01:00")
public class V1ListProcessorsResponse {
  @SerializedName("processors")
  private List<V1Processor> processors = null;

  public V1ListProcessorsResponse processors(List<V1Processor> processors) {
    this.processors = processors;
    return this;
  }

  public V1ListProcessorsResponse addProcessorsItem(V1Processor processorsItem) {
    if (this.processors == null) {
      this.processors = new ArrayList<V1Processor>();
    }
    this.processors.add(processorsItem);
    return this;
  }

   /**
   * Get processors
   * @return processors
  **/
  @ApiModelProperty(value = "")
  public List<V1Processor> getProcessors() {
    return processors;
  }

  public void setProcessors(List<V1Processor> processors) {
    this.processors = processors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ListProcessorsResponse v1ListProcessorsResponse = (V1ListProcessorsResponse) o;
    return Objects.equals(this.processors, v1ListProcessorsResponse.processors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(processors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ListProcessorsResponse {\n");
    
    sb.append("    processors: ").append(toIndentedString(processors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

