/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.conduit.client.model.V1Connector;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1ListConnectorsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-13T16:13:27.395+01:00")
public class V1ListConnectorsResponse {
  @SerializedName("connectors")
  private List<V1Connector> connectors = null;

  public V1ListConnectorsResponse connectors(List<V1Connector> connectors) {
    this.connectors = connectors;
    return this;
  }

  public V1ListConnectorsResponse addConnectorsItem(V1Connector connectorsItem) {
    if (this.connectors == null) {
      this.connectors = new ArrayList<V1Connector>();
    }
    this.connectors.add(connectorsItem);
    return this;
  }

   /**
   * Get connectors
   * @return connectors
  **/
  @ApiModelProperty(value = "")
  public List<V1Connector> getConnectors() {
    return connectors;
  }

  public void setConnectors(List<V1Connector> connectors) {
    this.connectors = connectors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ListConnectorsResponse v1ListConnectorsResponse = (V1ListConnectorsResponse) o;
    return Objects.equals(this.connectors, v1ListConnectorsResponse.connectors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(connectors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ListConnectorsResponse {\n");
    
    sb.append("    connectors: ").append(toIndentedString(connectors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

