/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.conduit.client.model.V1PluginSpecifications;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Deprecated: use ConnectorService.ListConnectorPlugins instead.
 */
@ApiModel(description = "Deprecated: use ConnectorService.ListConnectorPlugins instead.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-13T16:13:27.395+01:00")
public class V1ListPluginsResponse {
  @SerializedName("plugins")
  private List<V1PluginSpecifications> plugins = null;

  public V1ListPluginsResponse plugins(List<V1PluginSpecifications> plugins) {
    this.plugins = plugins;
    return this;
  }

  public V1ListPluginsResponse addPluginsItem(V1PluginSpecifications pluginsItem) {
    if (this.plugins == null) {
      this.plugins = new ArrayList<V1PluginSpecifications>();
    }
    this.plugins.add(pluginsItem);
    return this;
  }

   /**
   * Get plugins
   * @return plugins
  **/
  @ApiModelProperty(value = "")
  public List<V1PluginSpecifications> getPlugins() {
    return plugins;
  }

  public void setPlugins(List<V1PluginSpecifications> plugins) {
    this.plugins = plugins;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ListPluginsResponse v1ListPluginsResponse = (V1ListPluginsResponse) o;
    return Objects.equals(this.plugins, v1ListPluginsResponse.plugins);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plugins);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ListPluginsResponse {\n");
    
    sb.append("    plugins: ").append(toIndentedString(plugins)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

