/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Status describes the pipeline status.   - STATUS_RUNNING: Pipeline is running.  - STATUS_STOPPED: Pipeline gracefully stopped.  - STATUS_DEGRADED: Pipeline stopped with an error (see State.error).
 */
@JsonAdapter(V1PipelineStatus.Adapter.class)
public enum V1PipelineStatus {
  
  UNSPECIFIED("STATUS_UNSPECIFIED"),
  
  RUNNING("STATUS_RUNNING"),
  
  STOPPED("STATUS_STOPPED"),
  
  DEGRADED("STATUS_DEGRADED");

  private String value;

  V1PipelineStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static V1PipelineStatus fromValue(String text) {
    for (V1PipelineStatus b : V1PipelineStatus.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<V1PipelineStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final V1PipelineStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public V1PipelineStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return V1PipelineStatus.fromValue(String.valueOf(value));
    }
  }
}

