/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.conduit.client.model.V1PluginSpecificationsParameter;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Deprecated: use ConnectorPluginSpecifications instead.
 */
@ApiModel(description = "Deprecated: use ConnectorPluginSpecifications instead.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-13T16:13:27.395+01:00")
public class V1PluginSpecifications {
  @SerializedName("name")
  private String name = null;

  @SerializedName("summary")
  private String summary = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("author")
  private String author = null;

  @SerializedName("destinationParams")
  private Map<String, V1PluginSpecificationsParameter> destinationParams = null;

  @SerializedName("sourceParams")
  private Map<String, V1PluginSpecificationsParameter> sourceParams = null;

  public V1PluginSpecifications name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public V1PluginSpecifications summary(String summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @ApiModelProperty(value = "")
  public String getSummary() {
    return summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }

  public V1PluginSpecifications description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public V1PluginSpecifications version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public V1PluginSpecifications author(String author) {
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @ApiModelProperty(value = "")
  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public V1PluginSpecifications destinationParams(Map<String, V1PluginSpecificationsParameter> destinationParams) {
    this.destinationParams = destinationParams;
    return this;
  }

  public V1PluginSpecifications putDestinationParamsItem(String key, V1PluginSpecificationsParameter destinationParamsItem) {
    if (this.destinationParams == null) {
      this.destinationParams = new HashMap<String, V1PluginSpecificationsParameter>();
    }
    this.destinationParams.put(key, destinationParamsItem);
    return this;
  }

   /**
   * Get destinationParams
   * @return destinationParams
  **/
  @ApiModelProperty(value = "")
  public Map<String, V1PluginSpecificationsParameter> getDestinationParams() {
    return destinationParams;
  }

  public void setDestinationParams(Map<String, V1PluginSpecificationsParameter> destinationParams) {
    this.destinationParams = destinationParams;
  }

  public V1PluginSpecifications sourceParams(Map<String, V1PluginSpecificationsParameter> sourceParams) {
    this.sourceParams = sourceParams;
    return this;
  }

  public V1PluginSpecifications putSourceParamsItem(String key, V1PluginSpecificationsParameter sourceParamsItem) {
    if (this.sourceParams == null) {
      this.sourceParams = new HashMap<String, V1PluginSpecificationsParameter>();
    }
    this.sourceParams.put(key, sourceParamsItem);
    return this;
  }

   /**
   * Get sourceParams
   * @return sourceParams
  **/
  @ApiModelProperty(value = "")
  public Map<String, V1PluginSpecificationsParameter> getSourceParams() {
    return sourceParams;
  }

  public void setSourceParams(Map<String, V1PluginSpecificationsParameter> sourceParams) {
    this.sourceParams = sourceParams;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1PluginSpecifications v1PluginSpecifications = (V1PluginSpecifications) o;
    return Objects.equals(this.name, v1PluginSpecifications.name) &&
        Objects.equals(this.summary, v1PluginSpecifications.summary) &&
        Objects.equals(this.description, v1PluginSpecifications.description) &&
        Objects.equals(this.version, v1PluginSpecifications.version) &&
        Objects.equals(this.author, v1PluginSpecifications.author) &&
        Objects.equals(this.destinationParams, v1PluginSpecifications.destinationParams) &&
        Objects.equals(this.sourceParams, v1PluginSpecifications.sourceParams);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, summary, description, version, author, destinationParams, sourceParams);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1PluginSpecifications {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    destinationParams: ").append(toIndentedString(destinationParams)).append("\n");
    sb.append("    sourceParams: ").append(toIndentedString(sourceParams)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

