/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.conduit.client.model.PluginSpecificationsParameterValidation;
import io.conduit.client.model.V1PluginSpecificationsParameterType;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Deprecated: use config.v1.Parameter instead.
 */
@ApiModel(description = "Deprecated: use config.v1.Parameter instead.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-13T16:13:27.395+01:00")
public class V1PluginSpecificationsParameter {
  @SerializedName("description")
  private String description = null;

  @SerializedName("default")
  private String _default = null;

  @SerializedName("type")
  private V1PluginSpecificationsParameterType type = null;

  @SerializedName("validations")
  private List<PluginSpecificationsParameterValidation> validations = null;

  public V1PluginSpecificationsParameter description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public V1PluginSpecificationsParameter _default(String _default) {
    this._default = _default;
    return this;
  }

   /**
   * Get _default
   * @return _default
  **/
  @ApiModelProperty(value = "")
  public String getDefault() {
    return _default;
  }

  public void setDefault(String _default) {
    this._default = _default;
  }

  public V1PluginSpecificationsParameter type(V1PluginSpecificationsParameterType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public V1PluginSpecificationsParameterType getType() {
    return type;
  }

  public void setType(V1PluginSpecificationsParameterType type) {
    this.type = type;
  }

  public V1PluginSpecificationsParameter validations(List<PluginSpecificationsParameterValidation> validations) {
    this.validations = validations;
    return this;
  }

  public V1PluginSpecificationsParameter addValidationsItem(PluginSpecificationsParameterValidation validationsItem) {
    if (this.validations == null) {
      this.validations = new ArrayList<PluginSpecificationsParameterValidation>();
    }
    this.validations.add(validationsItem);
    return this;
  }

   /**
   * Get validations
   * @return validations
  **/
  @ApiModelProperty(value = "")
  public List<PluginSpecificationsParameterValidation> getValidations() {
    return validations;
  }

  public void setValidations(List<PluginSpecificationsParameterValidation> validations) {
    this.validations = validations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1PluginSpecificationsParameter v1PluginSpecificationsParameter = (V1PluginSpecificationsParameter) o;
    return Objects.equals(this.description, v1PluginSpecificationsParameter.description) &&
        Objects.equals(this._default, v1PluginSpecificationsParameter._default) &&
        Objects.equals(this.type, v1PluginSpecificationsParameter.type) &&
        Objects.equals(this.validations, v1PluginSpecificationsParameter.validations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, _default, type, validations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1PluginSpecificationsParameter {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    validations: ").append(toIndentedString(validations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

