/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit;

import java.util.List;

import io.conduit.client.model.Body;
import io.conduit.client.model.StreamResultOfV1InspectConnectorResponse;
import io.conduit.client.model.V1Connector;
import io.conduit.client.model.V1ConnectorPluginSpecifications;
import io.conduit.client.model.V1CreateConnectorRequest;
import io.conduit.client.model.V1DeleteConnectorResponse;
import io.conduit.client.model.V1ValidateConnectorRequest;
import io.conduit.client.model.V1ValidateConnectorResponse;
import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for ConnectorServiceApi
 */
@Ignore
public class ConnectorServiceApiTest {

    private final ConnectorServiceApi api = new ConnectorServiceApi();

    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void connectorServiceCreateConnectorTest() throws Exception {
        V1CreateConnectorRequest body = null;
        V1Connector response = api.connectorServiceCreateConnector(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void connectorServiceDeleteConnectorTest() throws Exception {
        String id = null;
        V1DeleteConnectorResponse response = api.connectorServiceDeleteConnector(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void connectorServiceGetConnectorTest() throws Exception {
        String id = null;
        V1Connector response = api.connectorServiceGetConnector(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void connectorServiceInspectConnectorTest() throws Exception {
        String id = null;
        StreamResultOfV1InspectConnectorResponse response = api.connectorServiceInspectConnector(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void connectorServiceListConnectorPluginsTest() throws Exception {
        String name = null;
        List<V1ConnectorPluginSpecifications> response = api.connectorServiceListConnectorPlugins(name);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void connectorServiceListConnectorsTest() throws Exception {
        String pipelineId = null;
        List<V1Connector> response = api.connectorServiceListConnectors(pipelineId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void connectorServiceUpdateConnectorTest() throws Exception {
        String id = null;
        Body body = null;
        V1Connector response = api.connectorServiceUpdateConnector(id, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void connectorServiceValidateConnectorTest() throws Exception {
        V1ValidateConnectorRequest body = null;
        V1ValidateConnectorResponse response = api.connectorServiceValidateConnector(body);

        // TODO: test validations
    }
    
}
