/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit;

import io.conduit.client.model.Apiv1Info;
import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for InformationServiceApi
 */
@Ignore
public class InformationServiceApiTest {

    private final InformationServiceApi api = new InformationServiceApi();

    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void informationServiceGetInfoTest() throws Exception {
        Apiv1Info response = api.informationServiceGetInfo();

        // TODO: test validations
    }
    
}
