/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit;

import java.util.List;

import io.conduit.client.api.PluginServiceApi;
import io.conduit.client.model.V1PluginSpecifications;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * API tests for PluginServiceApi
 */
@Disabled
public class PluginServiceApiTest {

    private final PluginServiceApi api = new PluginServiceApi();


    /**
     * Deprecated: use ConnectorService.ListConnectorPlugins instead.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void pluginServiceListPluginsTest() throws Exception {
        String name = null;
        List<V1PluginSpecifications> response = api.pluginServiceListPlugins(name);

        // TODO: test validations
    }

}
