/*
 * Conduit REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.conduit;

import java.util.List;

import io.conduit.client.api.ProcessorServiceApi;
import io.conduit.client.model.Body3;
import io.conduit.client.model.StreamResultOfV1InspectConnectorResponse;
import io.conduit.client.model.V1CreateProcessorRequest;
import io.conduit.client.model.V1DeleteProcessorResponse;
import io.conduit.client.model.V1Processor;
import io.conduit.client.model.V1ProcessorPluginSpecifications;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * API tests for ProcessorServiceApi
 */
@Disabled
public class ProcessorServiceApiTest {

    private final ProcessorServiceApi api = new ProcessorServiceApi();


    /**
     * @throws Exception if the Api call fails
     */
    @Test
    public void processorServiceCreateProcessorTest() throws Exception {
        V1CreateProcessorRequest body = null;
        V1Processor response = api.processorServiceCreateProcessor(body);

        // TODO: test validations
    }

    /**
     * @throws Exception if the Api call fails
     */
    @Test
    public void processorServiceDeleteProcessorTest() throws Exception {
        String id = null;
        V1DeleteProcessorResponse response = api.processorServiceDeleteProcessor(id);

        // TODO: test validations
    }

    /**
     * @throws Exception if the Api call fails
     */
    @Test
    public void processorServiceGetProcessorTest() throws Exception {
        String id = null;
        V1Processor response = api.processorServiceGetProcessor(id);

        // TODO: test validations
    }

    /**
     * InspectProcessorIn streams records coming into the specified processor
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void processorServiceInspectProcessorInTest() throws Exception {
        String id = null;
        StreamResultOfV1InspectConnectorResponse response = api.processorServiceInspectProcessorIn(id);

        // TODO: test validations
    }

    /**
     * InspectProcessorOut streams the output records from the specified processor
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void processorServiceInspectProcessorOutTest() throws Exception {
        String id = null;
        StreamResultOfV1InspectConnectorResponse response = api.processorServiceInspectProcessorOut(id);

        // TODO: test validations
    }

    /**
     * @throws Exception if the Api call fails
     */
    @Test
    public void processorServiceListProcessorPluginsTest() throws Exception {
        String name = null;
        List<V1ProcessorPluginSpecifications> response = api.processorServiceListProcessorPlugins(name);

        // TODO: test validations
    }

    /**
     * @throws Exception if the Api call fails
     */
    @Test
    public void processorServiceListProcessorsTest() throws Exception {
        List<String> parentIds = null;
        List<V1Processor> response = api.processorServiceListProcessors(parentIds);

        // TODO: test validations
    }

    /**
     * @throws Exception if the Api call fails
     */
    @Test
    public void processorServiceUpdateProcessorTest() throws Exception {
        String id = null;
        Body3 body = null;
        V1Processor response = api.processorServiceUpdateProcessor(id, body);

        // TODO: test validations
    }

}
